FROM node:22-alpine

WORKDIR /app

COPY package.json ./
COPY backend/package.json backend/package.json
COPY frontend/package.json frontend/package.json

RUN npm install

COPY backend ./backend
COPY .env.example ./.env

WORKDIR /app/backend

EXPOSE 5050

CMD ["npm", "start"]
